services:
  python:
    container_name: bor-dj
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/home/aventura-crm # Go one level up from docker-compose.yml and mount all the dirs
    entrypoint: /home/aventura-crm/entrypoint.sh
    mem_reservation: 1g
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: bor-pg-dj # Use this name in Connection/ip tab in pgadmin
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bor
      POSTGRES_PASSWORD: 659111
      POSTGRES_DB: boris
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump:/home/dump

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dj
    restart: always
    ports:
      - "80:80" # When adding new db server. In the connection tab use Host name / address: bor-db (container name, no need to use ip)
    environment:
      PGADMIN_DEFAULT_EMAIL: bor@bor.com # Pgadmin login
      PGADMIN_DEFAULT_PASSWORD: 659111 # Pgadmin pass
