# Generated by Django 5.1.5 on 2025-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language_code',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('nl', 'Dutch'), ('pt-br', 'Portuguese'), ('ru', 'Russian'), ('uk', 'Ukrainian')], default='', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='language_code',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('nl', 'Dutch'), ('pt-br', 'Portuguese'), ('ru', 'Russian'), ('uk', 'Ukrainian')], max_length=7, verbose_name='Language'),
        ),
    ]
